>LR
cli "CLI Entry"
parse_args "Parse Arguments"
load_cfg "Load Config"
validate_cfg:d "Validate Config"
init_log "Init Logger"
init_db "Init Database"
init_cache "Init Cache"
init_queue "Init Queue"
start_srv "Start Server"
route "Router"
mw_auth "Auth MW"
mw_rate "Rate Limiter"
mw_cors "CORS MW"
ctrl_user "User Controller"
ctrl_order "Order Controller"
ctrl_product "Product Controller"
svc_user "User Service"
svc_order "Order Service"
svc_product "Product Service"
repo_user "User Repository"
repo_order "Order Repository"
repo_product "Product Repository"
db_pool "DB Connection Pool"
cache_layer "Redis Cache"
queue_worker "Queue Worker"
email_svc "Email Service"
notify_svc "Notification Service"
health:o "Health Check"
metrics "Prometheus Metrics"
shutdown "Graceful Shutdown"

cli > parse_args "args"
parse_args > load_cfg "config path"
load_cfg > validate_cfg "raw config"
validate_cfg > init_log "valid"
validate_cfg > shutdown "invalid"
init_log > init_db "logger ready"
init_log > init_cache "logger ready"
init_log > init_queue "logger ready"
init_db > start_srv "db ready"
init_cache > start_srv "cache ready"
init_queue > start_srv "queue ready"
start_srv > route "listen"
route > mw_auth "request"
route > mw_rate "request"
route > mw_cors "request"
mw_auth > ctrl_user "authed"
mw_auth > ctrl_order "authed"
mw_auth > ctrl_product "authed"
ctrl_user > svc_user "call"
ctrl_order > svc_order "call"
ctrl_product > svc_product "call"
svc_user > repo_user "query"
svc_order > repo_order "query"
svc_product > repo_product "query"
repo_user > db_pool "sql"
repo_order > db_pool "sql"
repo_product > db_pool "sql"
svc_user > cache_layer "cache"
svc_order > cache_layer "cache"
svc_product > cache_layer "cache"
svc_order > queue_worker "async job"
queue_worker > email_svc "send"
queue_worker > notify_svc "push"
start_srv > health "probe"
start_srv > metrics "scrape"
start_srv > shutdown "SIGTERM"

@boot { cli parse_args load_cfg validate_cfg init_log init_db init_cache init_queue }
@middleware { mw_auth mw_rate mw_cors }
@controllers { ctrl_user ctrl_order ctrl_product }
@services { svc_user svc_order svc_product }
@repositories { repo_user repo_order repo_product }
@infra { db_pool cache_layer queue_worker email_svc notify_svc }
