>TB
gh_push "GitHub Push"
webhook "Webhook Receiver"
validate_sig:d "Validate Signature"
parse_event "Parse Event"
branch_check:d "Branch Filter"
lint_job "Lint Job"
eslint "ESLint"
prettier "Prettier"
stylelint "Stylelint"
typecheck "TypeScript Check"
lint_report "Lint Report"
test_unit "Unit Tests"
test_int "Integration Tests"
test_e2e "E2E Tests"
jest "Jest Runner"
playwright "Playwright"
coverage "Coverage Report"
test_report "Test Report"
build_fe "Build Frontend"
build_be "Build Backend"
build_docs "Build Docs"
webpack "Webpack Bundle"
esbuild "esbuild Bundle"
docgen "Doc Generator"
fe_artifact "FE Artifact"
be_artifact "BE Artifact"
docs_artifact "Docs Artifact"
scan_sast "SAST Scan"
scan_deps "Dependency Scan"
scan_secrets "Secret Scan"
scan_container "Container Scan"
security_report:h "Security Report"
docker_fe "Docker Build FE"
docker_be "Docker Build BE"
push_ecr_fe "Push ECR FE"
push_ecr_be "Push ECR BE"
deploy_staging "Deploy Staging"
smoke_test:o "Smoke Tests"
perf_test "Performance Test"
approval:d "Manual Approval"
deploy_prod "Deploy Production"
canary "Canary Deploy"
canary_check:d "Canary Health"
full_rollout "Full Rollout"
rollback:h "Rollback"
update_cdn "Update CDN"
invalidate_cache "Invalidate Cache"
notify_slack "Slack Notification"
notify_email "Email Notification"
update_jira "Update JIRA"
tag_release "Tag Release"
gen_changelog "Generate Changelog"
publish_npm "Publish npm"
gh_release "GitHub Release"
cleanup "Cleanup Artifacts"
monitor:o "Production Monitor"
alert:h "Alert Manager"
incident "Create Incident"
pagerduty "PagerDuty"
status_page "Status Page"
post_mortem "Post-mortem Log"

gh_push > webhook "event"
webhook > validate_sig "payload"
validate_sig > parse_event "valid"
parse_event > branch_check "event data"
branch_check > lint_job "main branch"
lint_job > eslint "run"
lint_job > prettier "run"
lint_job > stylelint "run"
lint_job > typecheck "run"
eslint > lint_report "result"
prettier > lint_report "result"
stylelint > lint_report "result"
typecheck > lint_report "result"
lint_report > test_unit "pass"
lint_report > test_int "pass"
lint_report > test_e2e "pass"
test_unit > jest "execute"
test_int > jest "execute"
test_e2e > playwright "execute"
jest > coverage "lcov"
jest > test_report "result"
playwright > test_report "result"
coverage > test_report "merge"
test_report > build_fe "pass"
test_report > build_be "pass"
test_report > build_docs "pass"
build_fe > webpack "src"
build_be > esbuild "src"
build_docs > docgen "md"
webpack > fe_artifact "bundle"
esbuild > be_artifact "bundle"
docgen > docs_artifact "html"
fe_artifact > scan_sast "code"
be_artifact > scan_sast "code"
fe_artifact > scan_deps "deps"
be_artifact > scan_deps "deps"
fe_artifact > scan_secrets "files"
be_artifact > scan_secrets "files"
scan_sast > security_report "findings"
scan_deps > security_report "findings"
scan_secrets > security_report "findings"
security_report > docker_fe "clear"
security_report > docker_be "clear"
docker_fe > scan_container "image"
docker_be > scan_container "image"
scan_container > security_report "findings"
docker_fe > push_ecr_fe "image"
docker_be > push_ecr_be "image"
push_ecr_fe > deploy_staging "deploy"
push_ecr_be > deploy_staging "deploy"
deploy_staging > smoke_test "url"
deploy_staging > perf_test "url"
smoke_test > approval "pass"
perf_test > approval "pass"
approval > deploy_prod "approved"
deploy_prod > canary "5% traffic"
canary > canary_check "metrics"
canary_check > full_rollout "healthy"
canary_check > rollback "unhealthy"
full_rollout > update_cdn "assets"
full_rollout > invalidate_cache "purge"
full_rollout > notify_slack "success"
full_rollout > notify_email "success"
full_rollout > update_jira "done"
full_rollout > tag_release "version"
tag_release > gen_changelog "tag"
tag_release > publish_npm "tag"
tag_release > gh_release "tag"
full_rollout > cleanup "done"
rollback > notify_slack "failure"
rollback > alert "trigger"
full_rollout > monitor "watch"
monitor > alert "anomaly"
alert > incident "critical"
alert > pagerduty "page"
alert > status_page "update"
incident > post_mortem "resolve"

@ci { lint_job eslint prettier stylelint typecheck lint_report }
@testing { test_unit test_int test_e2e jest playwright coverage test_report }
@build { build_fe build_be build_docs webpack esbuild docgen fe_artifact be_artifact docs_artifact }
@security { scan_sast scan_deps scan_secrets scan_container security_report }
@containers { docker_fe docker_be push_ecr_fe push_ecr_be }
@deploy { deploy_staging smoke_test perf_test approval deploy_prod canary canary_check full_rollout rollback }
@post_deploy { update_cdn invalidate_cache tag_release gen_changelog publish_npm gh_release cleanup }
@notifications { notify_slack notify_email update_jira }
@monitoring { monitor alert incident pagerduty status_page post_mortem }
